### ISSUE TITLE
Cannot run environment files 

### ISSUE THREAD

**Issue by saketh2002** [ScheiklP/sofa_env#31]
I was able to run python environment files until 2 weeks back, but suddenly I am not able to run environment files (reach.py) using python3 command . I am able to run ./runSofa with scene_description.py files. Please look into the error log below. I checked the docs and other old issues but could not find any similar issues. Apologies if there was any similar issue before and it was posted in docs. I even tried with sofa v22.06.00 version just to check it again
`Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/sofa/SOFA/v22.06.00/bin/.runSofa
---------------------------------------
[ERROR]   [RequiredPlugin(Sofa.Component.AnimationLoop)] Plugin not found: "Sofa.Component.AnimationLoop"
  
Failed to load: ["Sofa.Component.AnimationLoop"]
[ERROR]   [RequiredPlugin(Sofa.Component.Mapping.Linear)] Plugin not found: "Sofa.Component.Mapping.Linear"
  
Failed to load: ["Sofa.Component.Mapping.Linear"]
[ERROR]   [RequiredPlugin(Sofa.Component.ODESolver.Forward)] Plugin not found: "Sofa.Component.ODESolver.Forward"
  
Failed to load: ["Sofa.Component.ODESolver.Forward"]
[ERROR]   [RequiredPlugin(SofaPython3)] Plugin not found: "SofaPython3"
  
Failed to load: ["SofaPython3"]
[ERROR]   [RequiredPlugin(Sofa.Component.Mapping.NonLinear)] Plugin not found: "Sofa.Component.Mapping.NonLinear"
  
Failed to load: ["Sofa.Component.Mapping.NonLinear"]
[ERROR]   [RequiredPlugin(Sofa.Component.Constraint.Lagrangian.Model)] Plugin not found: "Sofa.Component.Constraint.Lagrangian.Model"
  
Failed to load: ["Sofa.Component.Constraint.Lagrangian.Model"]
[ERROR]   [RequiredPlugin(Sofa.Component.Engine.Select)] Plugin not found: "Sofa.Component.Engine.Select"
  
Failed to load: ["Sofa.Component.Engine.Select"]
[ERROR]   [RequiredPlugin(Sofa.Component.StateContainer)] Plugin not found: "Sofa.Component.StateContainer"
  
Failed to load: ["Sofa.Component.StateContainer"]
[ERROR]   [RequiredPlugin(Sofa.Component.Mass)] Plugin not found: "Sofa.Component.Mass"
  
Failed to load: ["Sofa.Component.Mass"]
[ERROR]   [RequiredPlugin(Sofa.Component.SceneUtility)] Plugin not found: "Sofa.Component.SceneUtility"
  
Failed to load: ["Sofa.Component.SceneUtility"]
[ERROR]   [RequiredPlugin(Sofa.Component.Constraint.Projective)] Plugin not found: "Sofa.Component.Constraint.Projective"
  
Failed to load: ["Sofa.Component.Constraint.Projective"]
[ERROR]   [RequiredPlugin(Sofa.Component.LinearSolver.Direct)] Plugin not found: "Sofa.Component.LinearSolver.Direct"
  
Failed to load: ["Sofa.Component.LinearSolver.Direct"]
[ERROR]   [RequiredPlugin(SofaGeneralRigid)] Plugin not found: "SofaGeneralRigid"
  
Failed to load: ["SofaGeneralRigid"]
[ERROR]   [RequiredPlugin(Sofa.Component.Collision.Detection.Algorithm)] Plugin not found: "Sofa.Component.Collision.Detection.Algorithm"
  
Failed to load: ["Sofa.Component.Collision.Detection.Algorithm"]
[ERROR]   [RequiredPlugin(SofaBoundaryCondition)] Plugin not found: "SofaBoundaryCondition"
  
Failed to load: ["SofaBoundaryCondition"]
[ERROR]   [RequiredPlugin(Sofa.Component.Topology.Container.Constant)] Plugin not found: "Sofa.Component.Topology.Container.Constant"
  
Failed to load: ["Sofa.Component.Topology.Container.Constant"]
[ERROR]   [RequiredPlugin(SofaEngine)] Plugin not found: "SofaEngine"
  
Failed to load: ["SofaEngine"]
[ERROR]   [RequiredPlugin(Sofa.Component.Collision.Detection.Intersection)] Plugin not found: "Sofa.Component.Collision.Detection.Intersection"
  
Failed to load: ["Sofa.Component.Collision.Detection.Intersection"]
[ERROR]   [RequiredPlugin(Sofa.Component.SolidMechanics.Spring)] Plugin not found: "Sofa.Component.SolidMechanics.Spring"
  
Failed to load: ["Sofa.Component.SolidMechanics.Spring"]
[ERROR]   [RequiredPlugin(ArticulatedSystemPlugin)] Plugin not found: "ArticulatedSystemPlugin"
  
Failed to load: ["ArticulatedSystemPlugin"]
[ERROR]   [RequiredPlugin(Sofa.Component.Visual)] Plugin not found: "Sofa.Component.Visual"
  
Failed to load: ["Sofa.Component.Visual"]
[ERROR]   [RequiredPlugin(Sofa.Component.LinearSolver.Iterative)] Plugin not found: "Sofa.Component.LinearSolver.Iterative"
  
Failed to load: ["Sofa.Component.LinearSolver.Iterative"]
[ERROR]   [RequiredPlugin(Sofa.Component.Collision.Response.Contact)] Plugin not found: "Sofa.Component.Collision.Response.Contact"
  
Failed to load: ["Sofa.Component.Collision.Response.Contact"]
[ERROR]   [RequiredPlugin(Sofa.GL.Component.Rendering3D)] Plugin not found: "Sofa.GL.Component.Rendering3D"
  
Failed to load: ["Sofa.GL.Component.Rendering3D"]
[ERROR]   [RequiredPlugin(Sofa.GL.Component.Shader)] Plugin not found: "Sofa.GL.Component.Shader"
  
Failed to load: ["Sofa.GL.Component.Shader"]
[ERROR]   [RequiredPlugin(Sofa.Component.IO.Mesh)] Plugin not found: "Sofa.Component.IO.Mesh"
  
Failed to load: ["Sofa.Component.IO.Mesh"]
[ERROR]   [RequiredPlugin(Sofa.Component.Setting)] Plugin not found: "Sofa.Component.Setting"
  
Failed to load: ["Sofa.Component.Setting"]
[ERROR]   [RequiredPlugin(Sofa.Component.Constraint.Lagrangian.Solver)] Plugin not found: "Sofa.Component.Constraint.Lagrangian.Solver"
  
Failed to load: ["Sofa.Component.Constraint.Lagrangian.Solver"]
[ERROR]   [RequiredPlugin(Sofa.Component.ODESolver.Backward)] Plugin not found: "Sofa.Component.ODESolver.Backward"
  
Failed to load: ["Sofa.Component.ODESolver.Backward"]
[ERROR]   [RequiredPlugin(Sofa.Component.Constraint.Lagrangian.Correction)] Plugin not found: "Sofa.Component.Constraint.Lagrangian.Correction"
  
Failed to load: ["Sofa.Component.Constraint.Lagrangian.Correction"]
[ERROR]   [RequiredPlugin(Sofa.Component.Collision.Geometry)] Plugin not found: "Sofa.Component.Collision.Geometry"
  
Failed to load: ["Sofa.Component.Collision.Geometry"]
[ERROR]   [SofaRuntime] ValueError: Object type BackgroundSetting<> was not created  
The object is not in the factory.  
This component has been MOVED from SofaBaseVisual to Sofa.Component.UserInterface.ConfigurationSetting since SOFA v22.06.
To continue using this component you may need to update your scene by adding
<RequiredPlugin name='Sofa.Component.UserInterface.ConfigurationSetting'/>  

Traceback (most recent call last):
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/scenes/reach/reach_env.py", line 435, in <module>
    env.reset()
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/scenes/reach/reach_env.py", line 380, in reset
    super().reset()
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/base.py", line 147, in reset
    self._init_sim()
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/scenes/reach/reach_env.py", line 216, in _init_sim
    super()._init_sim()
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/base.py", line 230, in _init_sim
    self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/scenes/reach/scene_description.py", line 98, in createScene
    add_scene_header(
  File "/home/sofa/SOFA/v22.06.00/bin/lapgym/sofa_env/sofa_env/sofa_templates/scene_header.py", line 172, in add_scene_header
    root_node.addObject("BackgroundSetting", color=background_color)
`

**Comment by ScheiklP** [comment]
I just pushed a commit to update the Plugin from which `BackgroundSetting` can be imported.
Could you pull this repo and try again?

**Comment by saketh2002** [comment]
Still showing same issue, I could even see the code lines changed, but still its showing the same log as above. Verified with v23.06.00, same issue.

**Comment by ScheiklP** [comment]
Should work now, with another new commit.
Sofa just had the wrong path in the warning. https://github.com/sofa-framework/sofa/pull/4860

**Comment by saketh2002** [comment]
I think I am missing something here, I am basically using the sofa_22.06.00 zip and extracting it, similarly for the 23.06.00 version, is it something that's not recommended ? Moreover, I find there are multiple such failures, after tried to comment out the line in scene_header.py that was causing the error, for example 
```
[ERROR]   [SofaRuntime] ValueError: Object type PositionalLight<> was not created  
The object 'PositionalLight' is not in the factory.  
This component has been MOVED from SofaOpenglVisual to Sofa.GL.Component.Shader since SOFA v22.06.
To continue using this component you may need to update your scene by adding
<RequiredPlugin name='Sofa.GL.Component.Shader'/>
``` 
But I am still able to run the scene description files, but not the env files, not sure where the issue is.

**Comment by ScheiklP** [comment]
That could be a mismatch with your python version. The precompiled version of sofa (that I do not recommend, exactly for that reason) is compiled with a specific version of SOFA. 23.06 was compiled with python3.8. https://github.com/sofa-framework/sofa/releases/tag/v23.06.00

You could try 24.06 with python 3.10 https://github.com/sofa-framework/sofa/releases/tag/v24.06.00

**Comment by saketh2002** [comment]
Can I run it via a conda env ? I usually use a PYTHONPATH parameter as specified in [Sofapython3 documentation](https://sofapython3.readthedocs.io/en/xp-readthedocs/content/UsingThePlugin.html) , Hence I was thinking if I could not use the PYTHONPATH (which is kind of like /home/sofa/SOFA/v23.06.00/plugins/SofaPython3/lib/python3/site-packages ).
On the alternative, what are some tips if I am going for cmake based installation of sofa ? I wanted to know if I could use docker. I have seen some documentation, but never tried it.

**Comment by saketh2002** [comment]
I was running the path in the wrong way all along and got stuck there. Apologies for my blunder. Thank you very much
